<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    
    <ItemGroup>
        <EmbeddedResource Include="..\lib-stripped\Celeste-icon.png">
            <LogicalName>%(EmbeddedResource.Identity)</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Include="SplashContent\**\*">
            <LogicalName>%(EmbeddedResource.Identity)</LogicalName>
        </EmbeddedResource>
    </ItemGroup>

</Project>
